var delay=100
var fcontent=new Array()
begintag='<font size=1>'
 
fcontent[0]="                  :                     <br>                  57i:.                 <br>                  7jrvuUU7:             <br>           .:i;LLYLU::,::7LY;,          <br>       7PUjLvr7i:.          ,rL:        <br>       .:7LYr;:                ir.      <br>            1i                   rr     <br>           r.                     i7    <br>          7,  ..,.                 r:   <br>         ,r  :.::Uv         ,ji..   Y   <br>         :,   :: MB         U rj.:  v.  <br>       ,iSi   jBBB8        ,kUBB    ::  <br>      .Y28k   ,BUYr        :BBBM    ji  <br>        .ur                 Y:.   .JMki <br>          U         .              LEi, <br>          ;2        i;,:;          J    <br>           iF,        .          rU     <br>             LYr.             ,7Yi      <br>              L7r7Yri:i:::;rLruu        <br>             7..   ,:77L77:.   :i       <br>            7 .:              ,  i.     <br>           iu:2,              .S:L:     <br>             ,v                7.       <br>" 
fcontent[1]="                  ;                     <br>                  BXY;.                 <br>                  FM10BBBXi             <br>           ,;LUNG88B7;i;7SZM1:          <br>       PBBMEN1FJ7:.         iUZr        <br>       ,7PG81U7.               Y1:      <br>            Bj                  .FU     <br>           U.                     Yk    <br>          ki                       S7   <br>         i1                         M   <br>         7:                         N,  <br>       :LBY                         vi  <br>      .OBBB  77ii:                  Mu  <br>        ,B1   :77:          7uLJr ,MBBY <br>         .B         .         .    EBJ: <br>          UB        ju:rU.        .M    <br>           JBi        ..         1B.    <br>            .0OU:             iFOY      <br>              Ek5q8FJ7L7vLuFE5BB        <br>             S:.   :LSP0kFv:   ij       <br>           .X ,;              i  u.     <br>           jB;B:              ,BL0L     <br>             iP                X,       <br>" 
fcontent[2]="                  :                     <br>                  57i:.                 <br>                  7jrvuUU7:             <br>           .:i;LLYLU::,::7LY;,          <br>       7PUjLvr7i:.          ,rL:        <br>       .:7LYr;:                ir.      <br>            1i                   rr     <br>           r.                     i7    <br>          7,  ..,.                 r:   <br>         ,r  :.::Uv         ,ji..   Y   <br>         :,   :: MB         U rj.:  v.  <br>       ,iSi   jBBB8        ,kUBB    ::  <br>      .Y28k   ,BUYr        :BBBM    ji  <br>        .ur                 Y:.   .JMki <br>          U         .              LEi, <br>          ;2        i;,:;          J    <br>           iF,        .          rU     <br>             LYr.             ,7Yi      <br>              L7r7Yri:i:::;rLruu        <br>             7..   ,:77L77:.   :i       <br>            7 .:              ,  i.     <br>           iu:2,              .S:L:     <br>             ,v                7.       <br>" 
fcontent[3]="                  ;                     <br>                  BXY;.                 <br>                  FM10BBBXi             <br>           ,;LUNG88B7;i;7SZM1:          <br>       PBBMEN1FJ7:.         iUZr        <br>       ,7PG81U7.               Y1:      <br>            Bj                  .FU     <br>           U.                     Yk    <br>          ki                       S7   <br>         i1                         M   <br>         7:                         N,  <br>       :LBY                         vi  <br>      .OBBB  77ii:                  Mu  <br>        ,B1   :77:          7uLJr ,MBBY <br>         .B         .         .    EBJ: <br>          UB        ju:rU.        .M    <br>           JBi        ..         1B.    <br>            .0OU:             iFOY      <br>              Ek5q8FJ7L7vLuFE5BB        <br>             S:.   :LSP0kFv:   ij       <br>           .X ,;              i  u.     <br>           jB;B:              ,BL0L     <br>             iP                X,       <br>" 
fcontent[4]="                  :                     <br>                  57i:.                 <br>                  7jrvuUU7:             <br>           .:i;LLYLU::,::7LY;,          <br>       7PUjLvr7i:.          ,rL:        <br>       .:7LYr;:                ir.      <br>            1i                   rr     <br>           r.                     i7    <br>          7,  ..,.                 r:   <br>         ,r  :.::Uv         ,ji..   Y   <br>         :,   :: MB         U rj.:  v.  <br>       ,iSi   jBBB8        ,kUBB    ::  <br>      .Y28k   ,BUYr        :BBBM    ji  <br>        .ur                 Y:.   .JMki <br>          U         .              LEi, <br>          ;2        i;,:;          J    <br>           iF,        .          rU     <br>             LYr.             ,7Yi      <br>              L7r7Yri:i:::;rLruu        <br>             7..   ,:77L77:.   :i       <br>            7 .:              ,  i.     <br>           iu:2,              .S:L:     <br>             ,v                7.       <br>" 
fcontent[5]="                   .L                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLuYYLJ::,:iJJL,         <br>         JZPUriii,..         :77:       <br>           ,iYui.              .;7      <br>             ii                  .v:    <br>            7.                     v:   <br>           7.  .,::                 J.  <br>          :i .:.:.U1          :,.   .Y  <br>          L.   LLiB8         5;i::,  v  <br>       .YJZv   BBBBJ        iu.BM ,  7. <br>        rLGi   iM:7         8BBB0    r  <br>          L.                rBiv   .;E, <br>          iL        ..             iMqY.<br>           j7       .r::i.         :5:  <br>            Lj.                   rL    <br>             .Jki.             .rui     <br>              i::vY7r:i:::::rrJN:       <br>             7..    ,irL7vrr.  ,:       <br>            7 .:              ,  i.     <br>           iU:2.              .5iL:     <br>             ,v                7.       <br>" 
fcontent[6]="                   .L                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLuYYLJ::,:iJJL,         <br>         JZPUriii,..         :77:       <br>           ,iYui.              .;7      <br>             ii                  .v:    <br>            7.                     v:   <br>           7.  .,::                 J.  <br>          :i .:.:.U1          :,.   .Y  <br>          L.   LLiB8         5;i::,  v  <br>       .YJZv   BBBBJ        iu.BM ,  7. <br>        rLGi   iM:7         8BBBN    r  <br>          L.                rBi7   .;E, <br>          iL         7Ur:       .  iOXY.<br>           j7        U10r      iri r1.  <br>            Lj.      rkY   .r.;:.q.L:.  <br>             .UPi.   ,J    .J :: .:Y:Y. <br>             ,:.:vY7i::.:::.YU      :YL <br>           :i. .    .ii77vr:,B:    :7   <br>          :Z: ,.             iJrY5P:    <br>            :7F.              :Y,:      <br>              r                i        <br>" 
fcontent[7]="                   .L                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLuYYLJ::,:iJJL,         <br>         JZPUriii,..         :77:       <br>           ,iYui.              .;7      <br>             ii                  .v:    <br>            7.                     v:   <br>           7.  .,::                 J.  <br>          :i .:.:.U1          :,.   .Y  <br>          L.   LLiB8         5;i::,  v  <br>       .YJZv   BBBBJ        iu.BM ,  7. <br>        ;LGi   iM:7         8BBBN    r  <br>          L.                rBi7   .i0, <br>      .   :v         7Ur:          :ESY.<br>   ,,,,,.. UL        U10r        i:rFi  <br>  . :  . ...ju.      rkY     7i;7.F2,:  <br>.,     .  ..  uPi.   ,J      ; .: ii7:i.<br>..,    .  ,  ,:.:vY7i::.::::iGi     :7L <br>  ,  , ....:i. .    .ii77vri,Er     :7: <br>   .,,:,, :0, ,.             :L7YL7r,   <br>            :7F.              :Y:i      <br>              r                i        <br>" 
fcontent[8]="                   .L                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLuYYLJ::,:iJJL,         <br>         JZPUriii,..         :77:       <br>           ,iYui.              .;7      <br>             ii                  .v:    <br>            7.                     v:   <br>           7.  .,::                 J.  <br>          :i .:.:.U1          :,.   .Y  <br>          L.   LLiB8         5;i::,  v  <br>       .YJZv   BBBBJ        iu.BM ,  7. <br>        ivGi   iM:7         8BBB0    r  <br>          7.                rBi7   .;E, <br>   .:ir:, :7         7Ur:          iGkY.<br>  :i7,::.;:NX.       U10r      .   :X:  <br>.i. i  , :;:vv.      rkY      ir7i:,r . <br>:7:    :  r:  uPi.   ,J       7. L Yi,7.<br> :7  : .  7  .:.:vY7i::.::::iXN     L7::<br>  :,,v:iri.,i. .    .ii77vri:2r.    .7L.<br>    ::r:. .0, ,.             :vYY:::::: <br>            :7F.              :Y;i..    <br>              r                :        <br>" 
fcontent[9]="                   .Y                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLjYYYJ::::ijjL,         <br>         JZqUriii,..        .:77:       <br>           ,iYU;.              .rr      <br>             ii                  .v:    <br>            7.                     7:   <br>           v.  .,::                 J.  <br>          :i .:.:.U2          :,..  .Y  <br>          L.   YLiB8         1;i:::  7  <br>        YJZv   BBBBJ        iU.BM ,  7. <br>        :rZi   iM:7         OBBBN    7  <br>    .ir:  i                 rBi7   .;0, <br>  :JFYUviiLUi:       7U;:          :ESY.<br> i: J. i.LYMP        U2Er        ::7Si  <br>iF: .  i ,Urr7.      7kY     7i;7.5U,i  <br>,Uv  : i  F7  uXi.   ,Y      ; .: :i7:i.<br> .1..U.:riL  ,:.:vL7i::.::::iGi     :7L <br>   i72UUL: .i. .    .ii77vr:,Er     :7: <br>          .E, ,.             :LvYY7r:   <br>           .:7F.              :Y:i      <br>              r                i        <br>" 
fcontent[10]="                   .Y                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLjYYYJ::::ijjL,         <br>         JZqUriii,..        .:77:       <br>           ,iYU;.              .rr      <br>             ii                  .v:    <br>            7.                     7:   <br>           v.  .,::                 J.  <br>          :i .:.:.U2          :,..  .Y  <br>          L.   YLiB8         1;i:::  7  <br>        YJGv   BBBBJ        iU.BM ,  7. <br>        i7Gi   iM:7         OBBBq    7  <br>          ;                 ;Bir   .;0, <br>   ijqE2r :r .       7U;:       .  i8XY.<br>  L2Mr7JiZkBBi       U2Er      i;i r5.  <br>,qi U  7 vZ57r.      7kY   .r.i: q.L:.  <br>vBv    L .OS  uXi.   ,Y    .Y :: .:Y:Y. <br> YO .U :  B: .:.:vL7i::.:::.YU      :Yv <br>  LrrBJFE1i.:. .    .ii77vr::B:    :7   <br>   .7uXj:  P, ,.             iYrY5P:    <br>            :7F.              :Y,:      <br>              r                i        <br>" 
fcontent[11]="                   .Y                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLjYYYJ::::ijjL,         <br>         JZqUriii,..        .:77:       <br>           ,iYU;.              .rr      <br>             ii                  .v:    <br>            7.                     7:   <br>           v.  .,::                 J.  <br>          :i .:.:.U2          :,..  .Y  <br>          L.   YLiB8         1;i:::  7  <br>       .YJGv   BBBBJ        iU.BM ,  7. <br>        i78i   iM:7         OBBBN    7  <br>          7.                rBi7   .;0, <br>    .:;:   :         7U;:          :ESY.<br>  rBBBBMUqr8XL       U2Er        ::7Si  <br> YY B. Y:MBBG5.      7kY     7i;7.5U,i  <br>YB7 :  2 rBM  JXi.   ,Y      ; .: :i7:i.<br>;B8 .; L  BS .:.:vL7i::.::::iGi     :7L <br> :B..B vjLM;,  .    .ii77vr:,Er     :7: <br>  .vZBBBB7,2. ,.             :LvYY7r:   <br>     ...    :7F.              :Y:i      <br>              r                i        <br>" 
fcontent[12]="                   .Y                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLjYYYJ::::ijjL,         <br>         JZqUriii,..        .:77:       <br>           ,iYU;.              .rr      <br>             ii                  .v:    <br>            7.                     7:   <br>           v.  .,::                 J.  <br>          :i .:.:.U2          :,..  .Y  <br>          L.   YLiB8         1;i:::  7  <br>       .YJGv   BBBBJ        iU.BM ,  7. <br>        i78i   iM:7         OBBBN    7  <br>          7.                rBi7   .;0, <br>    .:;:   :         7U;:          iGkY.<br>  rBBBBMUqr8XL       U2Er      ,   :P:  <br> YY B. Y:MBBG5.      7kY      irri:,r . <br>YB7 :  2 rBM  JXi.   ,Y       7  L Yi,7.<br>;B8 .; L  BS .:.:vL7i::.::::iXN     L7::<br> :B..B vjLM;,  .    .ii77vri:2r.    .7Y.<br>  .vZBBBB7,2. ,.             :vYL:::::: <br>     ...    :7F.              ,Y;i..    <br>              r                i        <br>" 
fcontent[13]="                   .Y                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLjYYYJ::::ijjL,         <br>         JZqUriii,..        .:77:       <br>           ,iYU;.              .rr      <br>             ii                  .v:    <br>            7.                     7:   <br>           v.  .,::                 J.  <br>          :i .:.:.U2          :,..  .Y  <br>          L.   YLiB8         1;i:::  7  <br>       .YJGv   BBBBJ        iU.BM ,  7. <br>        i78i   iM:7         OBBBN    7  <br>          7.                rBi7   .;0, <br>    .:;:   :         7U;:          :ESY.<br>  rBBBBMUqr8XL       U2Er        ::7Si  <br> YY B. Y:MBBG5.      7kY     7i;7.5U,i  <br>YB7 :  2 rBM  JXi.   ,Y      ; .: :i7:i.<br>;B8 .; L  BS .:.:vL7i::.::::iGi     :7L <br> :B..B vjLM;,  .    .ii77vr:,Er     :7: <br>  .vZBBBB7,2. ,.             :LvYY7r:   <br>     ...    :7F.              :Y:i      <br>              r                i        <br>" 
fcontent[14]="                   .Y                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLjYYYJ::::ijjL,         <br>         JZqUriii,..        .:77:       <br>           ,iYU;.              .rr      <br>             ii                  .v:    <br>            7.                     7:   <br>           v.  .,::                 J.  <br>          :i .:.:.U2          :,..  .Y  <br>          L.   YLiB8         1;i:::  7  <br>       .YJGv   BBBBJ        iU.BM ,  7. <br>        i78i   iM:7         OBBBq    7  <br>          7.                ;Bir   .;0, <br>    .:;:   :         7U;:       .  i8XY.<br>  rBBBBMUqr8XL       U2Er      i;i r5.  <br> YY B. Y:MBBG5.      7kY   .r.i: q.L:.  <br>YB7 :  2 rBM  JXi.   ,Y    .Y :: .:Y:Y. <br>;B8 .; L  BS .:.:vL7i::.:::.YU      :Yv <br> :B..B vjLM;,  .    .ii77vr::B:    :7   <br>  .vZBBBB7,2. ,.             iYrY5P:    <br>     ...    :7F.              :Y,:      <br>              r                i        <br>" 
fcontent[15]="                   .Y                   <br>                    U7i:                <br>                    vLrL2UJ:            <br>         ,,::;rLLjYYYJ::::ijjL,         <br>         JZqUriii,..        .:77:       <br>           ,iYU;.              .rr      <br>             ii                  .v:    <br>            7.                     7:   <br>           v.  .,::                 J.  <br>          :i .:.:.U2          :,..  .Y  <br>          L.   YLiB8         1;i:::  7  <br>       .YJGv   BBBBJ        iU.BM ,  7. <br>        i78i   iM:7         OBBBN    7  <br>          7.                rBi7   .rE, <br>    .:;:   :         7U;:          iMqY.<br>  rBBBBMUqr8XL       U2Er          :F:  <br> YY B. Y:MBBG5.      7kY          ;L    <br>YB7 :  2 rBM  LSi.   ,Y        .rui     <br>;B8 .; L  BE  i::vL7i::.::::rrJ0:       <br> :B..B vjYB  r,.    .ii77vri.  ::       <br>  .vZBBBBY  r .,              ,  i.     <br>     ...   iU:1.              .5iL:     <br>             ,v                7.       <br>" 
closetag='</font>'
var ie4=document.all&&!document.getElementById
var ns4=document.layers
var DOM2=document.getElementById
var index=0
function changecontent(){
if (index>=fcontent.length)
index=0
if (DOM2){
document.getElementById("fscroller").innerHTML=begintag+fcontent[index].replace(/ /g,"&nbsp;")+closetag
}
else if (ie4)
document.all.fscroller.innerHTML=begintag+fcontent[index].replace(/ /g,"&nbsp;")+closetag
else if (ns4){
document.fscrollerns.document.fscrollerns_sub.document.write(begintag+fcontent[index].replace(/ /g,"&nbsp;")+closetag)
document.fscrollerns.document.fscrollerns_sub.document.close()
}
index++
setTimeout("changecontent()",delay)
}
if (ie4||DOM2)
document.write('<div id="fscroller"></div>')
window.onload=changecontent